### ISSUE TITLE
doc: exposing ollama-webui-lite on the internet

### ISSUE THREAD

**Issue by c9482** [ollama-webui/ollama-webui-lite#14]
**Is your feature request related to a problem? Please describe.**
1. Created and deployed docker image for ollama-webui-lite
2. Created cloudflare tunnel to expose the container to the internet
3. Installed Ollama server as a service (not docker container)
4. The website starts and is accessible but cannot connect to ollama sever because of https error

![image](https://github.com/ollama-webui/ollama-webui-lite/assets/17013052/19993008-4571-4a08-88b8-03b903ca5457)

**Describe the solution you'd like**
Need a how-to document on strategies to expose ollama-webui-lite on the internet. 
1. Do I have to run ollama as a docker container?
2. Do I expose ollama service to the internet?

Environment is macOS Ventura (m2 chip)

**Comment by justinh-rahb** [comment]
When accessing the Ollama Web UI Lite over HTTPS, it's crucial that both the UI and the Ollama instance communicate using HTTPS. If your Ollama instance is not on the same machine as your browser, you might encounter a browser warning due to insecure resource requests.

This issue isn't directly related to the web UI or the project itself; instead, it's a security concern that arises from the communication between your browser and the Ollama instance.

To mitigate this issue, consider implementing one of the following solutions:

1. Use a Proxy: Set up an Nginx or other proxy between ollama-webui-lite and your Ollama instance. By doing so, all requests  will be routed through HTTPS, allowing you to bypass the browser warning. This requires some kind of tunnel or opening ports in firewall.

2. Utilize a Tunnel Service like ngrok: Ngrok is a free and easy-to-use tool for creating secure tunnels to local development servers. By using ngrok, you can expose your local Ollama instance over HTTPS and access it from the UI without triggering browser warnings. This requires no port forwarding, and is the quickest way I know of.

Both the proxy and ngrok solutions enable you to securely access your Ollama instance without encountering the browser warning related to mixed insecure resources. By implementing one of these methods, you ensure that all communication between your web UI and your Ollama instance is conducted over HTTPS.

**Comment by c9482** [comment]
Thank you. I followed your guidelines and got it all to work.
