### ISSUE TITLE
feat: restrict to a specific model and remove ability to pull/delete models

### ISSUE THREAD

**Issue by c9482** [ollama-webui/ollama-webui-lite#15]
For public access, it would be very useful to deploy ollama-webui-lite restricted to a specific model. Also, the Settings -> Models tab could be disabled. This could be a default or configurable via settings or environment variables.

**Comment by dangminhduc1101** [comment]
I think that as ollama-webui-lite currently stands, changing Models is considered a core functionality of the app. Also, the current codebase should be small enough so that removing this functionality and enforcing a default model should be not too difficult. After refactoring (which I hope to get started on and finish by February), the codebase should even be more easy to customize. Thoughts on this?

**Comment by c9482** [comment]
This sounds good. My use case is to run ollama-webui internally to test and deploy models, prompts, etc. The ollama-webui-lite would be deployed to the public with specific task in mind. It would be cool to be able to deploy the same docker image in multiple containers, each of them configured in specific way via environment variables.

I don't know svelte so I struggled my way through adding support for getting OLLAMA_API_BASE_URL from .env file today. No sure if contributing my changes makes sense since you will be refactoring everything anyway.

**Comment by c9482** [comment]
For what it's worth, here's the modified constants.ts that provides support for overriding OLLAMA_API_BASE_URL with environment variable:

```
import { env } from '$env/dynamic/public'

export const OLLAMA_API_BASE_URL = env.PUBLIC_OLLAMA_API_BASE_URL ?? `http://localhost:11434/api`;
export const WEB_UI_VERSION = "v0.0.1-lite";

```
